Keep namespace after test run with KEEP_NAMESPACE env
RedHatInsights/bonfire pull request #152
Opened 2021-11-12 17:07 UTC by psegedy

`KEEP_NAMESPACE` is unset or empty string -> release namespace
`KEEP_NAMESPACE` set to anything else -> set it to `TRUE` and keep namespace

it would be useful for debugging failing PR checks

2021-11-15 19:11 UTC, bsquizz requested changes
What if we use RELEASE_NAMESPACE env var -- by default set to true. If you do not want to release the namespace, set `RELEASE_NAMESPACE="false"` in your pr check.

2021-11-15 19:11 UTC, bsquizz commented on cicd/_common_deploy_logic.sh
> +#KEEP_NAMESPACE=TRUE  # keep namespace after PR check for time defaulty reserverd by bonfire (optional, default: unset)
```suggestion
#RELEASE_NAMESPACE="true"  # release namespace after PR check ends (default: true)
```

2021-11-15 19:11 UTC, bsquizz commented on cicd/_common_deploy_logic.sh
> +        if [ "${KEEP_NAMESPACE:+TRUE}" != "TRUE" ]; then
```suggestion
        if [ "${RELEASE_NAMESPACE:-true}" != "false" ]; then
```

2021-11-16 12:10 UTC, psegedy commented
makes sense, I've added your changes

2021-11-16 23:05 UTC, bsquizz approved these changes

2021-11-16 23:05 UTC, merged