[RHCLOUD-19866] Implement bonfire project command
RedHatInsights/bonfire pull request #234
Opened 2022-07-07 21:20 UTC by BlakeHolifield

Adds `bonfire project` as a cleaner interface for eph users to gather data about their openshfit project.
* Prints project name, ephemeral hostname for the frontend, and generated keycloak credentials

Example output
```
> bonfire project

Current project: ephemeral-2ncdi0
Frontend route: https://env-ephemeral-2ncdi0-thatsixdigitaddon.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com
Keycloak login: Username: jdoe || Password: notbase64pw
```

2022-07-26 15:04 UTC, maknop approved these changes

2022-07-26 17:12 UTC, bsquizz requested changes

2022-07-26 17:12 UTC, bsquizz commented on bonfire/namespaces.py
> +def project_exists(project_name: str):
You can remove this func if you make the changes I suggested within the `describe_` func

2022-07-26 17:12 UTC, bsquizz commented on bonfire/namespaces.py
> +    json_routes = json.loads(routes)
If you use get_json, this will already be a dict.

2022-07-26 17:12 UTC, bsquizz commented on bonfire/namespaces.py
> +    json_secret = json.loads(keycloak_secret)
If you use get_json, this will already be a dict.

2022-07-27 21:20 UTC, bsquizz approved these changes

2022-07-28 13:03 UTC, merged