Add dash y option to namespace reserve
RedHatInsights/bonfire pull request #246
Opened 2022-09-15 12:11 UTC by psav

2022-10-04 16:28 UTC, Victoremepunto commented on bonfire/bonfire.py
> +        "-y", "--no-prompt",
First - I'm surprised this hasn't arisen before. 
Second - this needs to be `-f` - I think.

2022-10-04 16:31 UTC, Victoremepunto requested changes

2022-10-04 16:31 UTC, Victoremepunto commented on bonfire/bonfire.py
> +        "-y", "--no-prompt",
yeah totally - `-f` and `--force` . `-y` paired with `--no-prompt` has a high "what was that option again" factor.

2022-10-11 17:28 UTC, bsquizz approved these changes
LGTM & tested manually

2022-10-11 17:28 UTC, merged