Cleanup CICD tool scripts
RedHatInsights/bonfire pull request #360
Opened 2024-04-17 19:49 UTC by mjholder

This downloads the cicd tools script into the TMP_JOB_DIR so that it will be deleted before being built into an image.

Related to this tickdt: https://issues.redhat.com/browse/RHCLOUD-32039

2024-04-17 20:19 UTC, bsquizz approved these changes
LGTM ... let me know when you tested it fully and are ready to merge

2024-04-18 09:11 UTC, Victoremepunto commented
@bsquizz  @mjholder  I think this can be superseded by !361

2024-04-18 09:14 UTC, Victoremepunto requested changes
Please, can you review #361 ? I think we don't need to write the script to disk at all, if you agree maybe we can close this and proceed with #361

2024-04-18 16:28 UTC, bsquizz approved these changes

2024-04-18 16:37 UTC, merged